# https://hub.docker.com/r/base/archlinux/
image: base/archlinux

before_script:
  - pacman -Syy dmd dub --needed --noconfirm
  - mkdir -p ~/.fixer
  - printf 'dummy' > ~/.fixer/api-access-key.txt

run_pylint:
  stage: test
  script: dub test
